name: Try auto merge

on:
  pull_request:
    branches: [ main ]
  # Allows to run this workflow manually from the Actions tab
  # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow 
  workflow_dispatch:

jobs:
  random-exit:
    runs-on: ubuntu-latest

    steps:
      - name: Exit
        run: exit 0

  check-files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Make sure change is on holiday files only
        run: | 
          updated_files=$(gh pr view "$PR_URL" --json files --jq '.files.[].path')
          for f in $updated_files; do
            echo $f
            if [[ ! $f =~ ^holiday/[a-zA-Z0-9_]+.dat$ ]]; then
              echo "${f} is not a holiday file. Failing test..."
              exit 1
            fi
          done

        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  automerge:
    runs-on: ubuntu-latest
    needs:
      - random-exit
      - check-files

    steps:
      - name: Merge PR
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
